import React, { useState, useRef, useEffect } from 'react';
import { ChatMessage, Message } from '../components/chat/ChatMessage';
import { GlassPanel } from '../components/common/GlassPanel';
import { Button } from '../components/common/Button';
import {
  Bot,
  Send,
  Sparkles,
  Terminal,
  Trash2,
} from 'lucide-react';

const API_BASE_URL = 'http://127.0.0.1:8000';

interface PredictionResponse {
  log_id: string;
  threat_probability: number;
  severity: string;
  shap_factors: {
    feature: string;
    impact: number;
  }[];
}

export const AiChatView: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'm-1',
      sender: 'AI',
      text:
        'Hello Analyst. I am CyberNex Security Co-Pilot. I can analyze telemetry using the trained XGBoost threat classifier and SHAP feature attribution. Enter a security query to begin analysis.',
      timestamp: new Date().toLocaleTimeString('en-US', {
        hour12: false,
      }),
    },
  ]);

  const [inputQuery, setInputQuery] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const chatEndRef = useRef<HTMLDivElement | null>(null);

  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({
      behavior: 'smooth',
    });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isTyping]);

  const buildTelemetryFromQuery = (query: string) => {
    const text = query.toLowerCase();

    let failed_logins = 2;
    let payload_len = 80;
    let sql_keywords = 0;
    let is_internal_ip = 0;
    let http_status = 200;
    let target_endpoint = '/api/v1/login';

    if (
      text.includes('sql') ||
      text.includes('injection') ||
      text.includes('database') ||
      text.includes('query')
    ) {
      failed_logins = 4;
      payload_len = 240;
      sql_keywords = 4;
      http_status = 500;
      target_endpoint = '/api/v1/login';
    } else if (
      text.includes('brute') ||
      text.includes('password') ||
      text.includes('login attack') ||
      text.includes('credential')
    ) {
      failed_logins = 18;
      payload_len = 70;
      sql_keywords = 0;
      http_status = 401;
      target_endpoint = '/api/v1/login';
    } else if (
      text.includes('xss') ||
      text.includes('script') ||
      text.includes('payload')
    ) {
      failed_logins = 3;
      payload_len = 420;
      sql_keywords = 1;
      http_status = 403;
      target_endpoint = '/api/v1/users';
    } else if (
      text.includes('internal') ||
      text.includes('trusted')
    ) {
      failed_logins = 3;
      payload_len = 100;
      sql_keywords = 1;
      is_internal_ip = 1;
      http_status = 200;
    }

    return {
      id: `log-${Date.now()}`,
      source_ip: '192.168.1.105',
      target_endpoint,
      failed_logins,
      payload_len,
      sql_keywords,
      is_internal_ip,
      http_status,
    };
  };

  const createAiResponse = (
    query: string,
    prediction: PredictionResponse
  ): Message => {
    const probability = Math.round(
      prediction.threat_probability * 100
    );

    const sortedFactors = [...prediction.shap_factors].sort(
      (a, b) => Math.abs(b.impact) - Math.abs(a.impact)
    );

    const topFactors = sortedFactors
      .slice(0, 3)
      .map(
        (factor) =>
          `${factor.feature}: ${
            factor.impact >= 0 ? '+' : ''
          }${factor.impact.toFixed(3)}`
      )
      .join(', ');

    let analysis = '';

    if (prediction.severity === 'CRITICAL') {
      analysis =
        `CRITICAL threat confidence detected at ${probability}%. ` +
        `The telemetry pattern requires immediate defensive investigation.`;
    } else if (prediction.severity === 'HIGH') {
      analysis =
        `HIGH threat confidence detected at ${probability}%. ` +
        `The telemetry contains multiple suspicious indicators.`;
    } else {
      analysis =
        `LOW threat confidence detected at ${probability}%. ` +
        `The current telemetry does not strongly indicate malicious activity.`;
    }

    return {
      id: `m-${Date.now()}-ai`,
      sender: 'AI',
      text:
        `Telemetry analysis completed for query: "${query}"\n\n` +
        `${analysis}\n\n` +
        `Detected severity: ${prediction.severity}\n` +
        `Threat probability: ${probability}%\n\n` +
        `Top SHAP contributing features: ${topFactors}\n\n` +
        `The result was generated by the CyberNex XGBoost classifier and its SHAP explanation layer.`,
      timestamp: new Date().toLocaleTimeString('en-US', {
        hour12: false,
      }),
      contextLogId: prediction.log_id,
    };
  };

  const handleSend = async () => {
    const query = inputQuery.trim();

    if (!query || isTyping) return;

    const userMsg: Message = {
      id: `m-${Date.now()}`,
      sender: 'USER',
      text: query,
      timestamp: new Date().toLocaleTimeString('en-US', {
        hour12: false,
      }),
    };

    setMessages((prev) => [...prev, userMsg]);
    setInputQuery('');
    setIsTyping(true);

    try {
      const telemetry = buildTelemetryFromQuery(query);

      const response = await fetch(`${API_BASE_URL}/api/predict`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(telemetry),
      });

      if (!response.ok) {
        throw new Error(
          `Backend returned HTTP ${response.status}`
        );
      }

      const prediction: PredictionResponse = await response.json();

      const aiMsg = createAiResponse(query, prediction);

      setMessages((prev) => [...prev, aiMsg]);
    } catch (error) {
      console.error('CyberNex AI backend error:', error);

      const errorMsg: Message = {
        id: `m-${Date.now()}-error`,
        sender: 'AI',
        text:
          'I could not connect to the CyberNex AI inference engine. ' +
          'Please make sure the FastAPI backend is running at ' +
          'http://127.0.0.1:8000 and the XGBoost model is loaded.',
        timestamp: new Date().toLocaleTimeString('en-US', {
          hour12: false,
        }),
      };

      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setIsTyping(false);
    }
  };

  return (
    <div className="p-6 max-w-[1400px] mx-auto h-[calc(100vh-5rem)] flex flex-col space-y-4">
      <div className="flex items-center justify-between bg-[#0B0B0D] p-4 rounded-xl border border-white/10">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-[#00F0FF]/10 border border-[#00F0FF]/30 text-[#00F0FF]">
            <Bot className="w-5 h-5" />
          </div>

          <div>
            <h1 className="text-lg font-bold font-mono text-white flex items-center gap-2">
              CYBERNEX AI CO-PILOT ASSISTANT
            </h1>

            <p className="text-xs text-gray-400 font-mono">
              XGBoost Threat Classifier • SHAP Explainability Engine
            </p>
          </div>
        </div>

        <Button
          size="sm"
          variant="outline"
          icon={<Trash2 className="w-3.5 h-3.5" />}
          onClick={() => setMessages([])}
        >
          Clear History
        </Button>
      </div>

      <div className="flex-1 bg-[#050505] rounded-xl border border-white/10 p-6 overflow-y-auto space-y-4">
        {messages.map((msg) => (
          <ChatMessage
            key={msg.id}
            message={msg}
            onExecuteAction={(act) =>
              alert(`Defensive action selected: ${act}`)
            }
          />
        ))}

        {isTyping && (
          <div className="flex items-center gap-2 text-xs font-mono text-[#00F0FF] animate-pulse py-2">
            <Sparkles className="w-4 h-4" />
            <span>
              CyberNex AI is running telemetry inference and SHAP analysis...
            </span>
          </div>
        )}

        <div ref={chatEndRef} />
      </div>

      <GlassPanel variant="card" className="p-3">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSend();
          }}
          className="flex items-center gap-3"
        >
          <div className="p-2 text-gray-500">
            <Terminal className="w-4 h-4" />
          </div>

          <input
            type="text"
            value={inputQuery}
            onChange={(e) => setInputQuery(e.target.value)}
            placeholder="Ask AI Co-Pilot to analyze SQL injection, brute force, XSS, or telemetry..."
            className="flex-1 bg-transparent border-none outline-none font-mono text-xs text-white placeholder-gray-500"
          />

          <Button
            type="submit"
            size="sm"
            variant="primary"
            icon={<Send className="w-3.5 h-3.5" />}
            disabled={!inputQuery.trim() || isTyping}
          >
            {isTyping ? 'Analyzing...' : 'Send'}
          </Button>
        </form>
      </GlassPanel>
    </div>
  );
};